[package]
name = "krpc"
version = "0.0.1"
authors = ["Cyclic3 <>"]
description = "The basic types for communicating with the Kerbal Space Program Remote Procedure Calls mod, implemented in rust"


[dependencies]
quick-protobuf = "^0.5.0"
